web/router.ex
defmodule DentalbookPartners.Router do
  use DentalbookPartners.Web, :router
  use Coherence.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session     
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true 
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser
    coherence_routes()
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end


  scope "/", DentalbookPartners do
    pipe_through :browser # Use the default browser stack
    get "/", PageController, :index
    get "/contrato", DealController, :show
    post "/contrato", DealController, :create
  end

  scope "/", DentalbookPartners do
    pipe_through :protected
    resources "/partners", PartnerController
    get "/companies/:company_id", CompanyController, :show
  end


  # Other scopes may use custom stacks.
  # scope "/api", DentalbookPartners do
  #   pipe_through :api
  # end
end

web/models/deal.ex
defmodule DentalbookPartners.Deal do
  use DentalbookPartners.Web, :model

  @primary_key false
  schema "deals" do
    field :partner_id, :integer
    field :content, :string
    
    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:partner_id, :content])
    |> validate_required([:partner_id, :content])
  end
end

web/controllers/deal_controller.ex
defmodule DentalbookPartners.DealController do
  use DentalbookPartners.Web, :controller
  alias DentalbookPartners.DealMounter.DealContent
  alias DentalbookPartners.Deal
  alias DentalbookPartners.Repo
  alias DentalbookPartners.Partner
  
  def show(conn, params) do
    IO.puts "representante"
    IO.inspect params
    partner = Repo.get_by(Partner, email: params["email"])
    render conn, "deal.html", partner: partner
  end

  def create(conn, params) do
    IO.puts "Salva o contrato no banco"
    IO.puts "Envia email do contrato para as partes"
    IO.puts "Redireciona para a tela de login"

    IO.inspect params

    params
    |> get_partner
    |> create_market_link
    |> fill_deal_content_to
    |> save

    conn
    |> put_flash(:info, "Sua conta foi criada com sucesso. Informe os dados abaixo para acessar sua área privativa.")
    |> redirect(to: session_path(conn, :new))
  end

  defp get_partner(%{"partner_id" => partner_id}), do: Repo.get(Partner, partner_id)

  defp create_market_link(partner) do
    partner
    |> get_splited_full_name
    |> make_market_link_of(partner)
    |> do_update(partner)
  end

  defp fill_deal_content_to(partner), do: DealContent.fill_for(partner)

  defp save(deal_content) do
    %Deal{}
    |> Deal.changeset(deal_content)
    |> Repo.insert
  end

  defp get_splited_full_name(partner) do 
    String.split(partner.name, " ") 
    |> Enum.reject(fn name_piece -> name_piece == "" end)
  end

  defp make_market_link_of(splited_name, of_partner) do
    name_for_link = Enum.count(splited_name) |> get_name_from(splited_name)

    "#{name_for_link}-#{of_partner.id}"
  end

  defp do_update(market_link, of_partner) do
    changes = %{"market_link" => market_link}
    of_partner
    |> Partner.changeset(changes)
    |> Repo.update

    of_partner
  end

  defp get_name_from(number_of_elements_in_name, splited_name) when number_of_elements_in_name == 1 do
    List.first(splited_name)
    |> String.downcase
  end

  defp get_name_from(_number_of_elements_in_name, splited_name) do
    "#{List.first(splited_name)}-#{List.last(splited_name)}"
    |> String.downcase
  end

end
  

web/views/deal_view.ex
defmodule DentalbookPartners.DealView do
  use DentalbookPartners.Web, :view
  alias DentalbookPartners.DealMounter.DealContent

  def show_filled_deal(partner) do
    DealContent.fill_for(partner)
    |> get_filled()
  end
  
  defp get_filled(%{content: content}), do: raw(content)
end

web/templates/deal/deal.html.eex
<style>
  .contract-action{
    position: fixed; 
    bottom: 0;
    left: 0;
    right: 0;
    height: 100px;
    background-color: #ffffff;
    width: 100%;
    border: 1px solid #1576c2;
  }

  .contract-action > a{
    margin-left: 20px;
    vertical-align: middle;
  }

  .btn-group-vertical:not(.bootstrap-select), .btn-group:not(.bootstrap-select){
    box-shadow: none;
  }

  .btn-shadow{
    box-shadow: 0 1px 4px 0 rgba(0, 0, 0, 0.3);
  }

  .no-plan{
    display: none;
  }

  .no-show{
    display: none;
  }

  .text-dark{
      margin-top: 1.5rem;
      margin-bottom: 1rem;
  }

  .footer-separation{
      margin-bottom: 8em;
  }

  #contract-content > p{
    text-align: justify;
  }

</style>

<form action="<%= deal_path(@conn, :create) %>" method="post">
    <input type="hidden" name="_csrf_token" value="<%= Plug.CSRFProtection.get_csrf_token() %>">
    <input type="hidden" name="partner_id", value="<%= @partner.id %>">

    <section id="contract-content" class="footer-separation">
      <%= show_filled_deal(@partner) %>
    </section>

    <footer class="contract-action text-center">
        <div class="mt-4 btn-group-no-shadow">
            <%= link "Não aceito os termos", to: Coherence.Config.logged_out_url("/"), class: "btn btn-danger w-md btn-bordered" %>
            <%= submit "Sim! Aceito os termos", class: "btn btn-primary w-md btn-bordered", id: "next-register-action" %>
        </div>

        <p class="text-dark" style="padding-left:20px; padding-right:20px;">
            Ao selecionar a opção "Sim! Aceito os termos" você assume ter lido e concordado com os termos e 
            condições do plano de representação apresentado.
        </p>
    </footer>
</form>